# Generated by Django 3.2.8 on 2021-10-12 09:29

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='library',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('book', models.CharField(max_length=250)),
                ('published', models.IntegerField()),
                ('exsheet', models.TextField()),
            ],
        ),
    ]
